add cron

diff --git a/.github/workflows/cron.yml b/.github/workflows/cron.yml
--- a/.github/workflows/cron.yml
+++ b/.github/workflows/cron.yml
@@ -12,36 +12,8 @@ jobs:
     runs-on: ubuntu-latest
     concurrency: build
     steps:
-      # - if: github.event_name!='workflow_dispatch'
-      #   name: sleep for pr
-      #   run: sleep 60
-      # - run: |
-      #     sudo apt-get update \
-      #     && sudo apt-get install -y wget gnupg \
-      #     && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - \
-      #     && sudo sh -c 'sudo echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
-      #     && sudo apt-get update \
-      #     && sudo apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
-      #       --no-install-recommends \
       - name: Check out repository code
         uses: actions/checkout@v3
-
-      # - uses: actions/setup-node@v3
-      #   with:
-      #     node-version: 16
-      #     cache: "npm"
-
-      # - name: Get npm cache directory
-      #   id: npm-cache-dir
-      #   run: |
-      #     echo "::set-output name=dir::$(npm config get cache)"
-      # - uses: actions/cache@v3
-      #   id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
-      #   with:
-      #     path: ${{ steps.npm-cache-dir.outputs.dir }}
-      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
-      #     restore-keys: |
-      #       ${{ runner.os }}-node-
       - name: install wrangler
         run: npm install -g wrangler
       - uses: denoland/setup-deno@v1
@@ -63,6 +35,7 @@ jobs:
           CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}
       - run: make install
       - run: make prod-source
+        id: source
         continue-on-error: true
         env:
           ARCHIVE_ACCESS_KEY_ID: ${{secrets.ARCHIVE_ACCESS_KEY_ID}}
@@ -93,8 +66,13 @@ jobs:
           DUFS_URL: ${{secrets.DUFS_URL}}
           DUFS_SECRETS: ${{secrets.DUFS_SECRETS}}
 
-      # - name: Publish pages
-      #   run: make prod-publish
-      #   env:
-      #     CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
-      #     CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}
+      - name: Publish pages
+        run: make prod-publish
+        env:
+          CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
+          CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}
+      - name: throw if source failed
+        if: steps.source.outcome == 'failure'
+        run: |
+          echo "::error::Source build failed"
+          exit 1
